[build]
builder = "NIXPACKS"
buildCommand = "cd frontend && npm ci && npm run build"

[deploy]
startCommand = "cd frontend && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
